spring:
  datasource:
    #    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: java.email.sender020@gmail.com
    password: haha112233!@#
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cashe: false


